spring:
  application:
    name: MovieListWithRatingService

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/library_db
#    username: root
#    password: rootpassword

#  jpa:
#    generate-ddl: true
#    properties:
#      jakarta:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: create.sql
#    show-sql: true
#    hibernate:
#      format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: '*' # Expose all endpoints
  endpoint:
    health:
      show-details: always # Show detailed health information

server:
  port: 3310

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3315/eureka/
      
      
      
      
resilience4j.circuitbreaker:
    configs:
        default:
            registerHealthIndicator: true
            slidingWindowSize: 100
            minimumNumberOfCalls: 5
            failureRateThreshold: 100
            waitDurationInOpenState: 20s
           # eventConsumerBufferSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            
       
        CB2:
            registerHealthIndicator: true
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: TIME_BASED
            minimumNumberOfCalls: 2
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            eventConsumerBufferSize: 10
          #  recordFailurePredicate: io.github.robwin.exception.RecordFailurePredicate
    instances:
        ratingServiceCircuitBreaker:
           baseConfig: CB2
           registerHealthIndicator: true
            
resilience4j.retry:
    instances:
        R1:
            maxAttempts: 3
            waitDuration: 10s
            enableExponentialBackoff: true
            exponentialBackoffMultiplier: 2
            retryExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.io.IOException
          #  ignoreExceptions:
         #       - io.github.robwin.exception.BusinessException
        R2:
            maxAttempts: 3
            waitDuration: 10s
            retryExceptions:
                - org.springframework.web.client.HttpServerErrorException
                - java.io.IOException
          #  ignoreExceptions:
         #       - io.github.robwin.exception.BusinessException
                
resilience4j.bulkhead:
    configs:
       default:
             maxWaitDuration: 10ms
             maxConcurrentCalls: 20
             
    instances:
        B1:
            maxConcurrentCalls: 10
        B2:
            maxWaitDuration: 10ms
            maxConcurrentCalls: 20
            
resilience4j.thread-pool-bulkhead:
  instances:
     TPB1:
      maxThreadPoolSize: 60
      coreThreadPoolSize: 40
      queueCapacity: 40
      writableStackTraceEnabled: true
  configs:
      default:
           maxThreadPoolSize: 5
           coreThreadPoolSize: 5
           queueCapacity: 5
           writableStackTraceEnabled: true
   
      
   
        
resilience4j.ratelimiter:
    instances:
        RL1:
            limitForPeriod: 10
            limitRefreshPeriod: 1s
            timeoutDuration: 0
            registerHealthIndicator: true
            eventConsumerBufferSize: 100
        RL2:
            limitForPeriod: 6
            limitRefreshPeriod: 500ms
            timeoutDuration: 3s
            
resilience4j.timelimiter:
    instances:
        TL1:
            timeoutDuration: 2s
            cancelRunningFuture: true
        TL2:
            timeoutDuration: 1s
            cancelRunningFuture: false

